FROM rust as builder
WORKDIR app
COPY . .
# This works with the dummy project generated by `cargo new app --bin`
RUN cargo build --release

FROM rust as runtime
COPY --from=builder /app/target/release/hackweek ./
ENTRYPOINT ["./hackweek"]
