apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackweek-rust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackweek
  template:
    metadata:
      labels:
        app: hackweek
    spec:
      containers:
      - name: hackweek-rust
        image: scures/hackweek:main
