apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: hackweek.hackweek.io
spec:
  group: hackweek.io
  version: v1
  names:
    kind: AppDeployment
    plural: hackweek
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
          properties:
            name:
              type: string
            namespace:
              type: string
        spec:
          type: object
          properties:
            image:
              type: string
            replicas:
              type: integer
        status:
          type: object
          properties:
            replicas:
              type: integer
            message:
              type: string
